### ISSUE TITLE
Ambiguity in generated sdk.go file for controllers.

### ISSUE THREAD

**Issue by vijtrip2** [aws/aws-controllers-k8s#101]
**Describe the bug**
Some of the autogenerated code throws error when building controller's main.go

**Steps to reproduce**
* Add '_ "github.com/aws/aws-controllers-k8s/services/apigatewayv2/pkg/resource/api"' to main.go file so that resourceManagerFactory is initialized.
* run go build -o ../../bin/controller main.go
* Following errors show up apart from https://github.com/aws/aws-controllers-k8s/issues/98
```
# github.com/aws/aws-controllers-k8s/services/apigatewayv2/pkg/resource/api
../../pkg/resource/api/sdk.go:61:3: undefined: tmpElem0
../../pkg/resource/api/sdk.go:61:36: elem0.ImportInfo undefined (type *string has no field or method ImportInfo)
../../pkg/resource/api/sdk.go:62:23: undefined: tmpElem0
../../pkg/resource/api/sdk.go:67:3: undefined: tmpElem1
../../pkg/resource/api/sdk.go:67:36: elem1.Warnings undefined (type *string has no field or method Warnings)
../../pkg/resource/api/sdk.go:68:23: undefined: tmpElem1
../../pkg/resource/api/sdk.go:108:3: undefined: tmpElem0
../../pkg/resource/api/sdk.go:108:36: elem0.ImportInfo undefined (type *string has no field or method ImportInfo)
../../pkg/resource/api/sdk.go:108:36: too many errors
```

* iteration should be performed on responseObject and not Ko.Status.ImportInfo
```
tmp0 := []*string{}
	for _, elem0 := range ko.Status.ImportInfo {
		tmpElem0.__listOf__string = elem0.ImportInfo
		tmp0 = append(tmp0, tmpElem0)
	}
	ko.Status.ImportInfo = tmp0
```

**Expected outcome**
Controller's main.go to build successfully

**Environment**

* Kubernetes version 1.14
* Using EKS (yes/no), if so version?  yes
* AWS service targeted (S3, RDS, etc.) apigatewayv2

**Comment by vijtrip2** [comment]
The above code fixes the original issue, but following is one more case where the generated code fails to build.

This bug is surfacing in sdkFind method for apigatewayv2 api resource. 
../../pkg/resource/api/sdk.go:64:3: undefined: f7elem


```
        ko.Status.APIEndpoint = resp.ApiEndpoint
	ko.Status.APIID = resp.ApiId
	ko.Status.CreatedDate = &metav1.Time{*resp.CreatedDate}
	f7 := []*string{}
	for _, f7iter := range resp.ImportInfo {
		f7elem.f7 = f7iter
		f7 = append(f7, f7elem)
	}
	ko.Status.ImportInfo = f7
```

The iteration for f7iter thrown exception for undefined variable.

**Comment by jaypipes** [comment]
Turns out this is happening because of APIGatewayV2's "Shapes that are structures but really are not structures but are actually just aliases for strings". Things like these:

```json
    "StringWithLengthBetween0And1024" : {
      "type" : "string"
    },
    "StringWithLengthBetween0And2048" : {
      "type" : "string"
    },
    "StringWithLengthBetween0And32K" : {
      "type" : "string"
    },
    "StringWithLengthBetween1And1024" : {
      "type" : "string"
    },
    "StringWithLengthBetween1And128" : {
      "type" : "string"
    },
    "StringWithLengthBetween1And1600" : {
      "type" : "string"
    },
    "StringWithLengthBetween1And256" : {
      "type" : "string"
    },
    "StringWithLengthBetween1And512" : {
      "type" : "string"
    },
    "StringWithLengthBetween1And64" : {
      "type" : "string"
    },
```

The code that is generating a constructor for fields that are defined like this:

```json
    "CreateRouteInput" : {
      "type" : "structure",
      "members" : {
...
        "AuthorizationScopes" : {
          "shape" : "AuthorizationScopes",
          "locationName" : "authorizationScopes"
        },
...
```

are looking at the `AuthorizationScopes` shape definition:

```json
    "AuthorizationScopes" : {
      "type" : "list",
      "member" : {
        "shape" : "StringWithLengthBetween1And64"
      }
    },
```

and getting confused because `StringWithLengthBetween1And64` is another `Shape` but is really just a string.
