### ISSUE TITLE
Identifying AWS resources created from ACK from perspective of service team.

### ISSUE THREAD

**Issue by vijtrip2** [aws/aws-controllers-k8s#105]
**Is your feature request related to a problem?**
API Gateway leadership wish to measure the success of onboarding with ACK by identifying the usage generated from API Gateway's onboarding with ACK.

**Describe the solution you'd like**
Up for discussion but maybe a tag that specifies when an aws resource is created from ACK controller.

**Describe alternatives you've considered**
None.

**Comment by jaypipes** [comment]
@vijtrip2 With the aws-sdk-go client calls now passing a custom User-Agent identifying the ACK service controller as being the originator of an API request, I think the only other thing this issue might entail is the AWS tags that an ACK service controller automatically attaches to a resource, but that is describe in #148. Can we close this issue out now?

**Comment by vijtrip2** [comment]
closing in favor of #148
