### ISSUE TITLE
Run integration tests against multiple kubernetes API versions

### ISSUE THREAD

**Issue by A-Hilaly** [aws/aws-controllers-k8s#111]
We need to ensure that ACK controllers operate correctly with the recent supported Kubernetes API versions. To guaranty that, we have to run the integration tests against multiple k8s API versions (at least recent patches of **1.18**, **1.17,** **1.16** and **1.15**). 

The easiest and fastest way to do this will be to spin kubernetes clusters using [kind](https://github.com/kubernetes-sigs/kind). A small [example](https://github.com/aws/aws-node-termination-handler/blob/master/test/k8s-local-cluster-test/provision-cluster) of how to provision multiple versions of k8s clusters using cluster

**Comment by scottmalkie** [comment]
Since kind also supports arm64, could this also be used to test architectural compatibility (x86 / arm) as well? Once EKS Arm support is GA, we expect a significant increase in demand for the rest of the EKS ecosystem to support Arm (in the form of Graviton/Graviton2-based instances.)

**Comment by A-Hilaly** [comment]
> Since kind also supports arm64, could this also be used to test architectural compatibility (x86 / arm) as well? Once EKS Arm support is GA, we expect a significant increase in demand for the rest of the EKS ecosystem to support Arm (in the form of Graviton/Graviton2-based instances.)

Good point. Right now we only test under amd64 architectures, and would be great to test for x86 and arm. I suppose this will not be supported any time soon (at least for the mvp) but for sure we need to cover it in the future. Let's open an issue to keep track of this.

**Comment by A-Hilaly** [comment]
#130 and #131 added KinD scripts to run integrations tests locally, next step is to run controllers tests against multiple K8s api versions during CircleCI pipelines

**Comment by smuralee** [comment]
* S3 service 
   - Integration tests successful with 1.18, 1.17, 1.16 and 1.15 on amd64
   - Integration testing on arm64 is work in progress

**Comment by smuralee** [comment]
Integration tests are failing for ECR and SNS

**Comment by jaypipes** [comment]
Folks, let's close this issue out and create specific issues for specific failures in integration tests.

**Comment by jaypipes** [comment]
@smuralee feel like creating issues for the SNS and ECR integration test failures, please?

**Comment by smuralee** [comment]
@jaypipes Added the issues - #280 and #281

**Comment by jaypipes** [comment]
> @jaypipes Added the issues - #280 and #281

Thank you @smuralee! Much appreciated! :)
