### ISSUE TITLE
Create a dedicated channel on Kubernetes community Slack

### ISSUE THREAD

**Issue by mhausenblas** [aws/aws-controllers-k8s#12]
Following the steps outlined in the Kubernetes [Slack guide](https://github.com/kubernetes/community/blob/master/communication/slack-guidelines.md#requesting-a-channel) create a channel `#aws-service-operator`.

**Comment by sd0408** [comment]
https://github.com/kubernetes/community/pull/4362

**Comment by mhausenblas** [comment]
Thanks a lot for taking on this @sd0408!

**Comment by sfzylad** [comment]
Created kubernetes/community#4468 since the other PR got stuck for a while now.

**Comment by mhausenblas** [comment]
Thanks for your work here @sfzylad and sorry for the delay in following up here. Reviewing kubernetes/community#4468 I will close this for now until we can make the case upstream that a dedicated channel is indeed needed (if we decide that this makes sense).
