### ISSUE TITLE
SNS controller error. 

### ISSUE THREAD

**Issue by nithu0115** [aws/aws-controllers-k8s#129]
**Describe the bug**
While building SNS controller, I am running into below issues

**Steps to reproduce**
```
/scripts/build-controller.sh sns
Building Kubernetes API objects for sns
Generating deepcopy code for sns
Generating custom resource definitions for sns
Building service controller for sns
Error: template: crd_sdk:59:15: executing "crd_sdk" at <GoCodeGetAttributesSetOutput .CRD "resp" "ko.Status" 1>: error calling GoCodeGetAttributesSetOutput: called GoCodeGetAttributesSetOutput for a resource 'GetPlatformApplicationAttributes' that doesn't unpack attributes map
Usage:
  ack-generate controller <service> [flags]
```

**Comment by jaypipes** [comment]
@nithu0115 do this:

```
ACK_GENERATE_CONFIG_PATH=pkg/model/testdata/models/apis/sns/0000-00-00/generate.yaml ./scripts/build-controller.sh sns
```

**Comment by jaypipes** [comment]
Eventually, that won't be necessary; until the `services/sns/generate.yaml` file exists permanently in the source repo, though, you need to provide instructions to the code generator how to handle the AttributesMap stuff. Those instructions are in here:

https://github.com/aws/aws-controllers-k8s/blob/mvp/pkg/model/testdata/models/apis/sns/0000-00-00/generator.yaml

**Comment by nithu0115** [comment]
Thanks @jaypipes. That worked 👍
