### ISSUE TITLE
README Link to documentation

### ISSUE THREAD

**Issue by ghostsquad** [aws/aws-controllers-k8s#160]
**Describe the bug**
The readme says:

> Documentation, including installation and usage instructions, are available online.

But there's no link to where these are "online".

**Comment by mhausenblas** [comment]
It's linked from the repo, directly: https://aws.github.io/aws-controllers-k8s/

But fair point, we should also make it part of the top-level README.

Note, however, that we're not yet in a position where e2e install works, we're still in the MVP phase (see #22).
