### ISSUE TITLE
Add project status badges

### ISSUE THREAD

**Issue by mhausenblas** [aws/aws-controllers-k8s#177]
We want to have [project status badges](https://shields.io/) incl. but not limited to [source code docs](https://pkg.go.dev/mod/github.com/aws/aws-controllers-k8s), [Go report](https://goreportcard.com/report/github.com/aws/aws-controllers-k8s) (BTW, nice job @jaypipes ;) and  CI (test, builds).

**Comment by scottmalkie** [comment]
I'll take this one as low-hanging fruit to ensure I'm doing PRs, etc. correctly before folding in multi-arch stuff.

**Comment by mhausenblas** [comment]
Thanks again, @scottmalkie and we should create another one once the CI pipeline is fully functioning and the container image push part can be covered as well/
