### ISSUE TITLE
Document the docs writing and testing better

### ISSUE THREAD

**Issue by mhausenblas** [aws/aws-controllers-k8s#184]
What we currently have in the [docs writing section](https://github.com/aws/aws-controllers-k8s/blob/main/docs/README.md) lacks detail (install, test) and causes contributors to spend, unnecessarily, time in setting up and updating their docs contributions.

**Comment by geoffcline** [comment]
PR #417 addressed this, 

https://github.com/aws/aws-controllers-k8s/pull/417/files includes info for contributors
