### ISSUE TITLE
Cant install from user docs install.md

### ISSUE THREAD

**Issue by danquack** [aws/aws-controllers-k8s#193]
**Describe the bug**
There doesn't appear to be any [releases](https://github.com/aws/aws-controllers-k8s/releases), and the index.yml file doesn't exist as described in the [install docs](https://github.com/aws/aws-controllers-k8s/blob/main/docs/contents/user-docs/install.md)

**Steps to reproduce**
https://aws.github.io/aws-controllers-k8s/index.yaml  -> returns 404
https://github.com/aws/aws-controllers-k8s/releases -> returns empty list
https://github.com/aws/aws-controllers-k8s/releases/download/v0.0.1/services/s3/all-resources.yaml  -> returns 404

**Expected outcome**
Either update documentation to reflect releases or provide local build instructions for deploying:
example include
- Release 0.0.1 as described in the docs
- Provide updated link on all-resources: to https://github.com/aws/aws-controllers-k8s/tree/main/services/s3
- Provide examples of how to install/use make file similar to comment here - https://github.com/aws/aws-controllers-k8s/pull/172#discussion_r470599839 

**Environment**
n/a

**Comment by mhausenblas** [comment]
Thanks and yes that's expected since it's a [developer preview](https://aws.github.io/aws-controllers-k8s/dev-docs/testing/) we will make available over the next couple of days.

**Comment by danquack** [comment]
@mhausenblas does that mean you will do a 0.0.1 release over the next few days? This confuses me, how can someone be in a developer preview, but you can’t install it

**Comment by mhausenblas** [comment]
@danquack did you check out https://aws.github.io/aws-controllers-k8s/dev-docs/testing/  already? That's the dev preview.
