### ISSUE TITLE
Add FAQ item on CDK/cdk8s

### ISSUE THREAD

**Issue by mhausenblas** [aws/aws-controllers-k8s#223]
Our [FAQ](https://aws.github.io/aws-controllers-k8s/community/faq/) should have an item that explains how ACK relates to CDK and cdk8s.

**Comment by joebowbeer** [comment]
The relationship with CDK is still undocumented.

**Comment by jaypipes** [comment]
> The relationship with CDK is still undocumented.

Hi @joebowbeer! Is there something specific that is missing from this FAQ:

https://aws.github.io/aws-controllers-k8s/community/faq/#cdk8s

that you feel needs to be explained about ACK and CDK8s?
