### ISSUE TITLE
Automate process of updating aws-sdk-go dependency

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-controllers-k8s#241]
As different AWS service APIs evolve and add new functionality, the aws-sdk-go source repository gets updated/regenerated. We should automatically upgrade our aws-sdk-go dependency when new releases are pushed out.

Things needed:

- [ ] Github Action step that runs periodically (nightly?) that, if it notices a new release of aws-sdk-go, automatically updates go.mod, creates a git commit and a PR with the updated dependency.

**Comment by JordanSussman** [comment]
I'd suggest using [dependabot](https://dependabot.com/) with the [allow](https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#allow) option to create a PR on periodic basis instead of relying on creating some GH Action workflow.

**Comment by r198809200** [comment]
對不起，請問這個程式是否可以遠端監控？

**Comment by mhausenblas** [comment]
@r198809200 would you mind phrasing your query in English, I want to make sure we understand unambiguously what you mean?

**Comment by DanStough** [comment]
PR #279 was created today by Dependabot. Seems like we're good to close this issue.
