### ISSUE TITLE
S3 bucket names to generated unique or randomly to avoid causing failures

### ISSUE THREAD

**Issue by phanimullapudi** [aws/aws-controllers-k8s#246]
**Is your feature request related to a problem?**

In smoke.sh - the bucket_name is set to a fixed name causing the S3 code to fail as there would be already a bucket_name with ack-test-smoke. So adding a random function in bash can avoid failures and avoid users to go again and change the code.

`bucket_name="ack-test-smoke-$service_name"`

**Describe the solution you'd like**

Add a random function to pass random values to the bucket-name or take input of that variable as part of the run instead.

**Describe alternatives you've considered**

I have manually modified the value in the smoke.sh.

**Comment by nithu0115** [comment]
Thanks for your Interest ACK @phanimullapudi . I think this issue is solved in #236
