### ISSUE TITLE
Automate the docs publishing process

### ISSUE THREAD

**Issue by mhausenblas** [aws/aws-controllers-k8s#264]
Currently the docs publishing process is manual, done by myself. We want to automate this process so that when a PR in the `docs/` dir is merged the site is published via `mkdocs gh-deploy`.

**Comment by geoffcline** [comment]
Quick status update

I have a github action working that builds and deploys the static site to a `gh-pages` branch, in response to any new commit to the `main` branch. I am using the `squidfunk/mkdocs-material` docker container. 

I also have an alternate configuration where the action deploys the site in response to a `run workflow` button in the github actions tab. 

The commits to the `gh-pages` appear from an `unknown` user. 

The action uses `--force` - I need to investigate further if that can be eliminated. I suspect that once the pages branch is on track with the action, it won't be necessary.

**Comment by geoffcline** [comment]
I had to fork the repo because github actions must be in the main branch to be usable. 

https://github.com/geoffcline/aws-controllers-k8s/blob/main/.github/workflows/mkdocs-deploy.yml

**Comment by mhausenblas** [comment]
> I had to fork the repo

Yes. That's both expected and recommended as per our [docs](https://aws.github.io/aws-controllers-k8s/dev-docs/setup/).

**Comment by mhausenblas** [comment]
Can you send in a PR?
