### ISSUE TITLE
Namespaced vs Cluster scoped resources?

### ISSUE THREAD

**Issue by ellistarn** [aws/aws-controllers-k8s#269]
Are all ACK resources namespaced, or will some of them be global? 

I'm thinking specifically about the eventual resources for EKS Managed Node Groups and EC2 Autoscaling Groups. These resources correspond to cluster global resources (nodes), and it's not clear to me whether or not they should be namespaced.

There may be other cases where it makes sense to have a globally scoped resource, e.g. Route53.

**Comment by jaypipes** [comment]
@ellistarn Hey Ellis! ALl ACK resources are namespaced. We get AWS account and region information from the Namespace's annotations.

**Comment by ellistarn** [comment]
Are you confident that this makes sense for Node Groups in the case where ACK is running inside a workload cluster (as opposed to a management cluster).

**Comment by jaypipes** [comment]
I don't really follow. What do you mean by "workload cluster"?

**Comment by ellistarn** [comment]
Sorry these are clusterapi terms. 

Management Cluster = control plane cluster which might house EKS Cluster ACK resources
Workload Cluster = standard EKS cluster where developers apply pods/deployments/services, etc

I'm assuming that ACK designed for both approaches.

EKS Cluster ACK resources must necessarily be in a Management Cluster due to a bootstrapping problem. EKS Node Groups could theoretically be applied to either. Other resources like DDB tables, etc, could be applied to either. 

It's not clear to me how namespacing plays into this. In the case where you have an ACK EKS Node Group in a workload cluster, should that resource be namespaced? The node resources that it creates aren't.
