### ISSUE TITLE
`ack-generate` can use old cached copy of aws-sdk-go models

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-controllers-k8s#291]
We were a bit stumped as to why @kumargauravsharma was generating service controller code for ECR that used an older version of `aws-sdk-go`'s structs in its `services/ecr/apis/v1alpha1/` output directory. But then Kumar stumbled upon the reason: `ack-generate` pulls via `git clone` the `aws-sdk-go` source repo into a local cache (by default, in `~/.cache/aws-controllers-k8s/src/aws-sdk-go` and uses that cached repo to access the model files that are themselves used to generate the Kubernetes CRD/API types.

And so what was happening is that Kumar had run `make build-controller SERVICE=ecr` at some point in the past before a newer version of `aws-sdk-go` was released that contained changes to the ECR API's models file. And thus `ack-generate` generated the API types that matched the old model instead of the new one.

There are a number of potential solutions to this problem:

1) Get rid of the local `~/.cache/aws-controllers-k8s/src/aws-sdk-go` cache entirely. Every time `ack-generate apis` (and thus every time `make build-controller`) is called, we would fetch the `api-2.json` and `doc-2.json` model files from the respective service directly from GitHub into a local build directory and direct `ack-generate` (and [its use of the `aws-sdk-go/private/model/api.Loader` functionality](https://github.com/aws/aws-controllers-k8s/blob/d4924a9722dcf0bbe063c4301b7badc59c3413fb/pkg/model/sdk_helper.go#L42-L100)) to use this local build directory.

2) Automatically, or upon some CLI flag (`--refresh-cache`?), `ack-generate` would call `git pull` on the `git clone`d copy of the `aws-sdk-go` source repository.

The second option is probably easier, IMHO.

**Comment by A-Hilaly** [comment]
+1 for the second option
