### ISSUE TITLE
service needs to be lower case ?

### ISSUE THREAD

**Issue by sebgoa** [aws/aws-controllers-k8s#302]
**Describe the bug**

First try at building a controller for SQS, I did `export SERVICE=SQS` and run into the following error, then I used the lower case...

```
Building Kubernetes API objects for SQS
Generating deepcopy code for SQS
Generating custom resource definitions for SQS
Building service controller for SQS
Generating RBAC manifests for SQS
queue/manager_factory.go:24:2: case-insensitive import collision: "github.com/aws/aws-controllers-k8s/services/sqs/pkg/resource" and "github.com/aws/aws-controllers-k8s/services/SQS/pkg/resource"
Error: not all generators ran successfully
run `controller-gen rbac:roleName=ack-controller paths=./... output:rbac:artifacts:config=/Users/sebgoa/go/src/github.com/sebgoa/aws-controllers-k8s/scripts/../services/SQS/config//rbac -w` to see all available markers, or `controller-gen rbac:roleName=ack-controller paths=./... output:rbac:artifacts:config=/Users/sebgoa/go/src/github.com/sebgoa/aws-controllers-k8s/scripts/../services/SQS/config//rbac -h` for usage
Running gofmt against generated code for SQS
(⎈ |k3d-foo:default)sebair:aws-controllers-k8s sebgoa$ export SERVICE=sqs
(⎈ |k3d-foo:default)sebair:aws-controllers-k8s sebgoa$ make build-controller SERVICE=$SERVICE
go build -tags codegen -ldflags "-X main.version="v0.0.0" -X main.buildHash=1b2910dcee44802f6c9fc1a9baeb2fe6598e7230 -X main.buildDate=2020-09-14T13:54:27Z" -o bin/ack-generate cmd/ack-generate/main.go
./scripts/build-controller.sh sqs
Building Kubernetes API objects for sqs
Generating deepcopy code for sqs
Generating custom resource definitions for sqs
Building service controller for sqs
Generating RBAC manifests for sqs
Running gofmt against generated code for sqs
```

**Steps to reproduce**

**Expected outcome**

it works first time

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by ChaturvediSulabh** [comment]
Can I take a gander at this?

**Comment by jaypipes** [comment]
> Can I take a gander at this?

@ChaturvediSulabh looks like @pgogia beat you to it :)

Are you looking for a place to contribute? How about this one? https://github.com/aws/aws-controllers-k8s/issues/199

**Comment by jaypipes** [comment]
Kind of similar problem to this one...

**Comment by ChaturvediSulabh** [comment]
Thanks, @jaypipes - I'll take a gander at #199. I'm not a pro, so may pop-up with questions and can work on it only after-hours, hence may take some time (is this fine)?

**Comment by jaypipes** [comment]
> Thanks, @jaypipes - I'll take a gander at #199. I'm not a pro, so may pop-up with questions and can work on it only after-hours, hence may take some time (is this fine)?

Totally fine! :) We're here to help. Alternately, feel free to find me on Kubernetes Slack #provider-aws channel!
