### ISSUE TITLE
Testing instructions need mockery as prereq

### ISSUE THREAD

**Issue by sebgoa** [aws/aws-controllers-k8s#325]
if we don't have `mockery` then

```
$ make kind-test SERVICE=$SERVICE
/bin/bash: ./bin/mockery: No such file or directory
tags=codegen --case=underscore --output=mocks/pkg/compare --dir=pkg/compare --all
/bin/bash: --case=underscore: command not found
make: [mocks/pkg/compare] Error 127 (ignored)
/bin/bash: ./bin/mockery: No such file or directory
tags=codegen --case=underscore --output=mocks/pkg/errors --dir=pkg/errors --all
/bin/bash: --case=underscore: command not found
make: [mocks/pkg/errors] Error 127 (ignored)
/bin/bash: ./bin/mockery: No such file or directory
```

it needs to be added to the prereq list at [https://aws.github.io/aws-controllers-k8s/dev-docs/testing/](https://aws.github.io/aws-controllers-k8s/dev-docs/testing/
)

**Comment by A-Hilaly** [comment]
Hi @sebgoa! This is planned in #268

**Comment by jaypipes** [comment]
Closing this out. If you run the test scripts, we now check for mockery and fail early if it isn't installed. We even have a helper `scripts/install-mockery.sh` script to help install it, and the error message calls out this script.
