### ISSUE TITLE
Defined Graduation Criteria for Beta & GA of a service controller

### ISSUE THREAD

**Issue by tabern** [aws/aws-controllers-k8s#339]
**Is your feature request related to a problem?**
There's no established criteria for graduating a service controller for Beta or GA. These are critical if we want to clearly track where a controller stands and estimate the work required to release it for production use.

**Describe the solution you'd like**
For any given controller, we need a list of criteria (assets created, tests executed, functional capabilities, time in use, etc) that we can use as a checklist to plan and evaluate the eligibility for the status of the controller.

**Comment by mhausenblas** [comment]
Some thoughts:

- Beta: gotta be usable (Helm chart, etc.) and stable (overall API/UX should not change)
- GA: fully tested (as set out in #6 and that includes scale and soak tests)
