### ISSUE TITLE
Code generator does not identify top-level resources (CRDs) for ApplicationAutoscaling: API Operations begin with "Register" and "Put"

### ISSUE THREAD

**Issue by mbaijal** [aws/aws-controllers-k8s#391]
**Describe the bug**
ACK for the application autoscaling service does not generate resources (config/crd/bases) since the code generator identifies top-level resources (CRDs) by looking for API Operations that begin with "Create". The Application Autoscaling API uses `RegisterScalableTarget` and `PutScalingPolicy` instead. 

**Steps to reproduce**
1. `make build-controller SERVICE=applicationautoscaling`
2. `./scripts/kind-build-test.sh -s applicationautoscaling`
The second command fails with the error `applicationautoscaling/config/crd/bases does not exist`

**Expected outcome**
The controller manager docker image be build to install the service operator. 

**Environment**

* Kubernetes version
* Using EKS (yes/no), if so version? No, using the existing scripts on Kind. 
* AWS service targeted (S3, RDS, etc.) - ApplicationAutoscaling (For SageMaker)

**Comment by jaypipes** [comment]
Yep, the heuristic we use in ACK to determine "what is a CRD?" is dead simple: does there exist a `Create` API call for the resource? I think the solution here is to add something to the `generatorConfig` that can instruct the code generator that certain API calls should be treated as "Create" API calls.
