### ISSUE TITLE
Documentation and test framework to validate multi controller nodes setup

### ISSUE THREAD

**Issue by kumargauravsharma** [aws/aws-controllers-k8s#436]
**Is your feature request related to a problem?**
Consider scenario where multiple instances of ACK service controller are deployed on K8s cluster. 
This feature request is to have documentation, test framework to test multi controller nodes deployment.

**Describe the solution you'd like**
Documentation and test framework to validate multi controller nodes setup

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by mhausenblas** [comment]
Closing this since it's a dupe of #435
