### ISSUE TITLE
Elasticache Snapshot Support

### ISSUE THREAD

**Issue by kumargauravsharma** [aws/aws-controllers-k8s#455]
**Is your feature request related to a problem?**
Enable Snapshot support from ACK service controller for Amazon ElastiCache

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Comment by jaypipes** [comment]
Resource manager code merged. Still needs e2e tests added.
