### ISSUE TITLE
AWS RabbitMQ service controller

### ISSUE THREAD

**Issue by liu0013** [aws/aws-controllers-k8s#466]
## ACK Service Controller
Support for AWS RabbitMQ - https://aws.amazon.com/about-aws/whats-new/2020/11/announcing-amazon-mq-rabbitmq/

### Checklist for Dev Preview
- [ ] Code generation (`make build-controller`)
- [ ] End-to-end test (`make kind-test`)
- [ ] Docs are updated, at least:
  - [ ] [testing](https://aws.github.io/aws-controllers-k8s/dev-docs/testing/) 
  - [ ] [svc controller listing](https://aws.github.io/aws-controllers-k8s/services/)
- [ ] Container image in public registry

**Comment by jaypipes** [comment]
Hi @liu0013, we have an issue for Amazon MQ here: https://github.com/aws/aws-controllers-k8s/issues/390

Since RabbitMQ is just a feature of the Amazon MQ service, I'm going to close this ticket out.
