### ISSUE TITLE
IAM service controller

### ISSUE THREAD

**Issue by mdykes-gw** [aws/aws-controllers-k8s#484]
## New ACK Service Controller

Support for IAM

### List of API resources

List the API resources in order of importance to you:

1) [resource 1]
1) [resource 2]

**Comment by jaypipes** [comment]
Hi @mdykes-gw, the IAM service controller is proposed in #222. Closing this one out and please add any comments/feedback about IAM resources you'd like to see supported in ACK to #222.

**Comment by mdykes-gw** [comment]
Thanks for the info @jaypipes ! Don't know how I missed #222 , but I did.

**Comment by jaypipes** [comment]
No worries! 😃
