### ISSUE TITLE
Mailing list link in the README doesn't work

### ISSUE THREAD

**Issue by giuscri** [aws/aws-controllers-k8s#517]
**Describe the bug**
Link in the README https://groups.google.com/forum/#!forum/aws-service-operator-user doesn't redirect to a valid mailing list.

**Comment by mhausenblas** [comment]
I'm not sure what you mean. It does redirect there, maybe you need to be signed in?

That said, good call, we should likely either rename or remove the ML since we're not using it (all comm is via GitHub issues and Slack).

WDYT @jaypipes?

**Comment by jaypipes** [comment]
> I'm not sure what you mean. It does redirect there, maybe you need to be signed in?
> 
> That said, good call, we should likely either rename or remove the ML since we're not using it (all comm is via GitHub issues and Slack).
> 
> WDYT @jaypipes?

Yeah, let's remove the mailing list @mhausenblas. I think GH issues and Slack are more than enough communication channels.
