### ISSUE TITLE
Loading template files dynamically

### ISSUE THREAD

**Issue by muvaf** [aws/aws-controllers-k8s#538]
**Is your feature request related to a problem?**

We have the Crossplane Provider generation but it doesn't use all of the template files that are used in ACK output and the main reasons are that ACK generates a full-blown controller that can be installed on its own (Helm chart, RBAC and other YAMLs) and the amount of code shared between the controllers is different. However, since the [list of template files](https://github.com/aws/aws-controllers-k8s/blob/de6a699/pkg/generate/template.go#L29) is static, we had to include all `.tpl` files even if they were not used so that generation succeeds.

**Describe the solution you'd like**

We can have the generator accept a certain list of template files to use. For example, we can have a `Templates` struct in [`generate.go`](https://github.com/aws/aws-controllers-k8s/blob/de6a699/pkg/generate/template.go#L29) with fields like `ConfigFiles`, `ReleaseCopyFiles` etc. Then we can supply the correct lists when we initialize that object and give it to the function it'll be used.

ACK template files would live in `templates/ack` and Crossplane template files would live under `templates/crossplane` folder.

**Describe alternatives you've considered**

Scan the folders and include all `.tpl` files. This would work if we differentiate by folder name but given that we'll have 2 set of template files in all cases, seems like overkill.

cc @jaypipes I can tackle this this week.

**Comment by jaypipes** [comment]
@muvaf I've already got parts of this done :) I'll use this issue number to track. Expect a PR for it later today or tomorrow.

**Comment by muvaf** [comment]
@jaypipes Great, thank you!

**Comment by muvaf** [comment]
Fixed by https://github.com/aws/aws-controllers-k8s/pull/546 Thanks @jaypipes !
