### ISSUE TITLE
Is this only supported on EKS or can I run it on any k8s cluster?

### ISSUE THREAD

**Issue by red8888** [aws/aws-controllers-k8s#556]
I use google cloud and gke

Can I install this on a gke cluster to create aws resources?

**Comment by jaypipes** [comment]
Hi @red8888! You can absolutely install ACK service controllers on GKE Kubernetes clusters! There is nothing specific to EKS about ACK at all.

**Comment by red8888** [comment]
Oh cool thanks! I had trouble finding the docs for installing and setting it up. Is there a helm chart for installing this?

**Comment by jaypipes** [comment]
> Oh cool thanks! I had trouble finding the docs for installing and setting it up. Is there a helm chart for installing this?

There will be very shortly. We are publishing our Helm charts and Docker images to a new ECR public registry. Should be done by end of this week.
