### ISSUE TITLE
Route 53 Resolver service controller

### ISSUE THREAD

**Issue by bwagner5** [aws/aws-controllers-k8s#591]
## New ACK Service Controller

Support for Route 53 Resolver
### List of API resources

List the API resources in order of importance to you:

1) [ResolverEndpoint](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverEndpoint.html)
1) [ResolverRule](https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53resolver_CreateResolverRule.html)

**Comment by jaypipes** [comment]
@bwagner5 I've consolidated these into https://github.com/aws/aws-controllers-k8s/issues/480.
