### ISSUE TITLE
VPC security groups service controller

### ISSUE THREAD

**Issue by dustnic** [aws/aws-controllers-k8s#623]
## New ACK Service Controller

Support for VPC security groups.

(this could be particularly useful in combination with SGs for PODs and the SecurityGroupPolicy resource)

### List of API resources

List the API resources in order of importance to you:

1) Security Group

**Comment by jaypipes** [comment]
Hi @dustnic! Please see issue #489 for the VPC service controller. I'm going to close this out as a duplicate of that issue and have added `SecurityGroup` to the list of resources to build out on that issue. Please let me know if you disagree with this.
