### ISSUE TITLE
[Documentation]  Dev-docs is not clear about how to install correct controller-gen binary

### ISSUE THREAD

**Issue by prashao** [aws/aws-controllers-k8s#633]
**Describe the bug**
The developer docs are not very clear on how to install the correct controller-gen binary. There are a couple of issues #234 and #259 that attempt to address it but they don't offer absolute clarity. 

**Steps to reproduce**
- GOPATH should be set 
- Because of #259 one would try to install controller-gen directly from  https://github.com/kubernetes-sigs/controller-tools as -
   go get github.com/kubernetes-sigs/controller-tools/cmd/controller-gen
But it leads to following errors 
   $ go get github.com/kubernetes-sigs/controller-tools
             go: github.com/kubernetes-sigs/controller-tools upgrade => v0.4.1
             go get: github.com/kubernetes-sigs/controller-tools@v0.4.1: parsing go.mod:
              module declares its path as: sigs.k8s.io/controller-tools
              but was required as: github.com/kubernetes-sigs/controller-tools

- This issue is of kubernetes-sigs repo and can be resolved in the following way
   go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.1
  
- Now the problem is that aws-controller-k8s requires controller-gen v0.4.0 
   $ make build-controller SERVICE=s3
building ack-generate ... ok.
FATAL: Existing version of controller-gen Version: v0.4.1, required version is v0.4.0.
FATAL: Please uninstall controller-gen and install the required version with scripts/install-controller-gen.sh. 

- Now the user has to remove v0.4.1 and run scripts/install-controller-gen.sh to get the desired version.

**Expected outcome**
I think the docs should have indicated to use  scripts/install-controller-gen.sh in the Prerequisites section where it mentions kubernetes-sigs/controller-tools 
It should also indicate that just the controller-gen binary is required from controller-tools. 

**Environment**
Linux

* Kubernetes version
* Using EKS (yes/no), if so version? 
* AWS service targeted (S3, RDS, etc.)

**Comment by jaypipes** [comment]
@prashao are you interested in submitting a PR that updates our docs here?

**Comment by prashao** [comment]
Yeah. I will submit a PR for this one.
What about the other issues related to cluster reuse I told you about? Should I submit issues & PR for those as well?

**Comment by prashao** [comment]
Fixed through #651
