### ISSUE TITLE
Aurora Serverless Service Controller

### ISSUE THREAD

**Issue by wreed4** [aws/aws-controllers-k8s#9]
## ACK Service Controller
Support for **Aurora Serverless**

### Checklist for Dev Preview
- [ ] Code generation (`make build-controller`)
- [ ] End-to-end test (`make kind-test`)
- [ ] Docs are updated, at least:
  - [ ] [testing](https://aws.github.io/aws-controllers-k8s/dev-docs/testing/) 
  - [ ] [svc controller listing](https://aws.github.io/aws-controllers-k8s/services/)
- [ ] Container image in public registry

**Comment by masoom** [comment]
This is highly anticipated by a Telco Giant. Much appreciated Jay

**Comment by jaypipes** [comment]
This is being worked as part of the overall RDS service controller here:

https://github.com/aws/aws-controllers-k8s/issues/237

I am closing this one down since it's a component of RDS.
