### ISSUE TITLE
Incorrect Snake cases for normalized names

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-controllers-k8s#97]
For some initialisms and acronyms, snake casing is producing incorrect output. Snake case is used primarily to generate clean package names for resources.

An example problematic initialism is "Uri", which is part of the word "Security". The normalization process in `pkg/names/names.go` for snake-casing the name "CacheSecurityGroup" is outputting "cache_sec_uri_ty_group" instead of "cache_security_group". Fun!

**Comment by A-Hilaly** [comment]
Fixed in #107
